/*
 *  Copyright 2019 Faycel B. Beji & Deep Dive Coding
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package edu.cnm.deepdive.relevant.model.entity;


import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import com.google.gson.annotations.Expose;
import java.io.Serializable;
import java.util.Date;

/**
 * Encapsulates the attributes of a the url for this instance. Room and GSon annotations are used to
 * specify entity &amp; attribute mapping for database persistence, and property mapping for JSON
 * serialization/deserialization mapping.
 */

@Entity(
    indices = {@Index(value = "url", name = "url", unique = true)}

)
/**
 * Returns the autogenerated primary key of this instance.
 *
 * @return primary key value.
 */
public class Search implements Serializable {

  @ColumnInfo(name = "category_id", index = true)
  private long categoryId;

  @ColumnInfo(name = "search_id")
  @PrimaryKey(autoGenerate = true)
  private long id;

  @ColumnInfo(index = true)
  private Date date;

  @ColumnInfo(name = "user_id", index = true)
  private long userId;

  @ColumnInfo(name = "url")
  private String url;

  @Expose
  private String title;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Date getDate() {
    return date;
  }

  public void setDate(Date date) {
    this.date = date;
  }

  public long getUserId() {
    return userId;
  }

  public void setUserId(long userId) {
    this.userId = userId;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public long getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(long categoryId) {
    this.categoryId = categoryId;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }
}


