package edu.cnm.deepdive.relevant.model.entity;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

@Entity
public class User {

  /**
   * Returns the autogenerated primary key of this instance.
   *
   * @return primary key value.
   */

  @ColumnInfo(name = "user_id")
  @PrimaryKey(autoGenerate = true)
  private long id;

  @ColumnInfo(name = "Search_id", index = true)
  private long searchId;

  public long getSearchId() {
    return searchId;
  }

  public void setSearchId(long searchId) {
    this.searchId = searchId;
  }

  @ColumnInfo(index = true)
  private String name ;


  @ColumnInfo(index = true)
  private String lastName ;

  @ColumnInfo(index = true)
  private String email ;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

}